
import type { Metadata } from 'next';
import { BlogPostCard } from "@/components/blog/BlogPostCard";
import { latestBlogPosts, categories } from "@/lib/data";
import { Newspaper, RefreshCw, AlertTriangle } from "lucide-react";
import { generateMultipleBlogPosts } from '@/ai/flows/generate-multiple-blog-posts-flow';
import type { BlogPost } from '@/types';

export const metadata: Metadata = {
  title: 'Latest Financial News & Market Updates',
  description: 'Get the latest financial news, stock market updates, and expert analysis from MarketPulse. Your source for timely share market insights.',
  alternates: {
    canonical: '/news',
  },
  openGraph: {
    title: 'Latest Financial News & Market Updates | MarketPulse',
    description: 'Get the latest financial news, stock market updates, and expert analysis from MarketPulse.',
    url: '/news',
  },
};

// Revalidate this page on every request to get fresh AI content
export const revalidate = 0; 

const SectionTitle = ({ title, icon: Icon, description }: { title: string; icon?: React.ElementType; description?: string; }) => (
  <div className="mb-8">
    <div className="flex items-center gap-2 mb-2">
      {Icon && <Icon className="h-7 w-7 text-primary" />}
      <h1 className="font-headline text-3xl font-bold">{title}</h1>
    </div>
    {description && <p className="text-muted-foreground">{description}</p>}
  </div>
);

export default async function NewsPage() {
  let aiPosts: BlogPost[] = [];
  let fetchError = false;

  try {
    // Generate 3 fresh blog posts from AI
    aiPosts = await generateMultipleBlogPosts({ count: 3 });
  } catch (error) {
    console.error("Error fetching AI-generated news:", error);
    fetchError = true;
  }

  const staticPosts = latestBlogPosts.slice(0, 3); // Show some static posts as well

  return (
    <div className="container py-8 md:py-12">
      <SectionTitle 
        title="Today's AI-Generated News" 
        icon={RefreshCw}
        description="Fresh perspectives generated by MarketPulse AI. Content may vary on refresh."
      />
      {fetchError && (
        <div className="mb-8 p-4 bg-destructive/10 border border-destructive text-destructive-foreground rounded-md flex items-center gap-2">
          <AlertTriangle size={20} />
          <p>Could not load fresh AI-generated news at the moment. Showing archived content.</p>
        </div>
      )}
      {aiPosts.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
          {aiPosts.map((post) => (
            <BlogPostCard key={post.slug} post={post} orientation="vertical" />
          ))}
        </div>
      ) : !fetchError ? (
         <p className="text-lg text-muted-foreground mb-12">Generating fresh news... If this takes too long, please try refreshing.</p>
      ) : null}

      <SectionTitle title="From Our Archives" icon={Newspaper} />
      {staticPosts.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {staticPosts.map((post) => (
            <BlogPostCard key={post.id} post={post} orientation="vertical" />
          ))}
        </div>
      ) : (
        <p className="text-lg text-muted-foreground">No archived news articles available at the moment.</p>
      )}
    </div>
  );
}
